# Add appropriate URL schemes to entries in the clubs table
select 'clubemail', count(*), substring_index(clubemail , ':', 1) as scheme from clubs where clubemail  like '%:%' group by scheme union select 'clubemail', count(*), 'bare' from clubs where clubemail not like '%:%' and clubemail <> '' union select 'clubemail', count(*), '' from clubs where clubemail = '' union select 'total', count(*), '' from clubs;
UPDATE clubs SET clubemail = concat('mailto:', clubemail) where clubemail <> '' and not clubemail like 'mailto:%';
select 'clubemail', count(*), substring_index(clubemail , ':', 1) as scheme from clubs where clubemail  like '%:%' group by scheme union select 'clubemail', count(*), 'bare' from clubs where clubemail not like '%:%' and clubemail <> '' union select 'clubemail', count(*), '' from clubs where clubemail = '' union select 'total', count(*), '' from clubs;

select 'clubwebsite', count(*), substring_index(clubwebsite , ':', 1) as scheme from clubs where clubwebsite  like '%:%' group by scheme union select 'clubwebsite', count(*), 'bare' from clubs where clubwebsite not like '%:%' and clubwebsite <> '' union select 'clubwebsite', count(*), '' from clubs where clubwebsite = '' union select 'total', count(*), '' from clubs;
UPDATE clubs SET clubwebsite = concat('http:', clubwebsite) where clubwebsite <> '' and not clubwebsite like 'http:%';
select 'clubwebsite', count(*), substring_index(clubwebsite , ':', 1) as scheme from clubs where clubwebsite  like '%:%' group by scheme union select 'clubwebsite', count(*), 'bare' from clubs where clubwebsite not like '%:%' and clubwebsite <> '' union select 'clubwebsite', count(*), '' from clubs where clubwebsite = '' union select 'total', count(*), '' from clubs;

select 'facebook', count(*), substring_index(facebook , ':', 1) as scheme from clubs where facebook  like '%:%' group by scheme union select 'facebook', count(*), 'bare' from clubs where facebook not like '%:%' and facebook <> '' union select 'facebook', count(*), '' from clubs where facebook = '' union select 'total', count(*), '' from clubs;
UPDATE clubs SET facebook = concat('https:', facebook) where facebook <> '' and not facebook like 'https:%';
select 'facebook', count(*), substring_index(facebook , ':', 1) as scheme from clubs where facebook  like '%:%' group by scheme union select 'facebook', count(*), 'bare' from clubs where facebook not like '%:%' and facebook <> '' union select 'facebook', count(*), '' from clubs where facebook = '' union select 'total', count(*), '' from clubs;

select 'twitter', count(*), substring_index(twitter , ':', 1) as scheme from clubs where twitter  like '%:%' group by scheme union select 'twitter', count(*), 'bare' from clubs where twitter not like '%:%' and twitter <> '' union select 'twitter', count(*), '' from clubs where twitter = '' or twitter is null union select 'total', count(*), '' from clubs;
UPDATE clubs SET twitter = concat('https:', twitter) where twitter <> '' and not twitter like 'https:%';
select 'twitter', count(*), substring_index(twitter , ':', 1) as scheme from clubs where twitter  like '%:%' group by scheme union select 'twitter', count(*), 'bare' from clubs where twitter not like '%:%' and twitter <> '' union select 'twitter', count(*), '' from clubs where twitter = '' or twitter is null union select 'total', count(*), '' from clubs;